### ISSUE TITLE
add the need of gcc

### ISSUE THREAD

**Issue by pfennigbube** [AimPizza/todo-md-rs#4]
maybe not as big but gcc should be installed on the system before you can cargo install it.. 
so maybe just add it into your readme.txt that you need to have any gnu compiler installed
_ig its different for every system if they have it or not so maybe let them check_

**Comment by AimPizza** [comment]
Thanks for pointing that out!
I just tested this issue on a blank Debian VM and it seems that most dependencies are installed by default. Not having gcc installed seems to only be a problem on distros that require more experience to begin with so I'm not sure _if_ or how we should include that requirement without starting to list most basic GNU utils.
My idea to make the installation process smoother would be to note that git and rust are needed (perhaps link to [their docs](https://doc.rust-lang.org/cargo/getting-started/installation.html) on installing the rust toolchain) because that might be something the average user could stumble over.
Another idea would be to create more extensive installation instructions in [the Wiki](https://github.com/AimPizza/todo-md-rs/wiki) and link to it from the README. There, we could list pitfalls of specific distros such as, _cough_, NixOS.

Ideally, this tedious way of installing the tool should become redundant once it's packaged properly but I haven't looked into that yet.

**Comment by pfennigbube** [comment]
Thank you for the addition! Yea I would also just link the wikis that _should_ work fine for most distros _cough_ nixos not tho.
So your idea with adding it into the installation section should be the best!
If the error comes on it's easy to troubleshoot anyway because it says that gcc is missing.
Thank you for.taking your time!

**Comment by AimPizza** [comment]
Hope that's about it. Feel free to open a PR if you see room for improvement, though.
